version: "3.7"
services:
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    restart: always
